const mongoose = require('mongoose');
const { Schema, Types } = mongoose;

const userSchema = new Schema({
  name:                                       { type: String, required: true },
  email:                                      { type: String, required: true, unique: true },
  email_verified_at:                          { type: Date },
  password:                                   { type: String, required: true },
  remember_token:                             { type: String },
  profile_photo_path:                         { type: String },
  two_factor_secret:                          { type: String },
  two_factor_recovery_codes:                  { type: String },
  two_factor_confirmed_at:                    { type: Date },
  google_id:                                  { type: String },
  google_token:                               { type: String },
  google_refresh_token:                       { type: String },
  avatar:                                     { type: String },
  phone:                                      { type: String },
  company_id:                                 { type: Types.ObjectId, ref: 'Company' },
  api_key:                                    { type: String },
  api_secret:                                 { type: String },
  site_url:                                   { type: String },
  company_name:                               { type: String },
  note:                                       { type: String },
  payment:                                    { type: Number },
  company_logo:                               { type: String },
  license_quota:                              { type: Number, default: 1 },
  locale:                                     { type: String },
  label_method:                               { type: String, default: 'shipping_company' },
  label_type:                                 { type: String, default: 'default' },
  display_logo:                               { type: Boolean },
  sms_template:                               { type: String, default: 'shipping_created' },
  wix_shipping_method_for_shipping_point:     { type: String },
  shopify_shipping_method_for_shipping_point: { type: String },
  package_id:                                 { type: Types.ObjectId, ref: 'Package' },
  package_updated_date:                       { type: Date },
  trackerPage_id:                             { type: Types.ObjectId, ref: 'TrackerPage' },
  trackerPage_contact_info:                   { type: Schema.Types.Mixed },
  display_order_product:                      { type: Boolean, default: true },
  display_product_price_in_order_detail:      { type: Boolean, default: true },
  display_order_price:                        { type: Boolean, default: false },
  display_order_number_barcode:               { type: Boolean, default: false },
  display_total_shipment:                     { type: Boolean, default: false },
  can_use_collection_point:                   { type: Boolean, default: true },
  enable_sort_by_warehouse:                   { type: Boolean, default: false },
  sort_by_warehouse:                          { type: Boolean, default: false },
  enable_api:                                 { type: Boolean, default: false },
  allow_shipos_delivery:                      { type: Boolean, default: false },
  shipos_delivery_id:                         { type: Types.ObjectId, ref: 'ShiposDelivery' },
  support_phone:                              { type: String },
  support_email:                              { type: String },
  google_api_key:                             { type: String },
}, { timestamps: true });

module.exports = mongoose.model('User', userSchema);
